### ISSUE TITLE
gpio incorrectly assumes 0 value by default

### ISSUE THREAD

**Issue by neojski** [EnotionZ/gpio#34]
In [set](https://github.com/EnotionZ/GpiO/blob/89700222960d8060e78644cdb5bde4744669922c/lib/gpio.js#L194) there's comparison of current value with the new one. But current value is not read from hardware but assumed to be `0` by default. Therefore if gpio is high I cannot make it back low.

**Comment by cinderblock** [comment]
This is not exactly a bug with this `GpiO` package. The linux sysfs gpio interface specifies that the output starts as low unless the direction is set to `high` instead of `out`. See #38 for more.

**Comment by mmajchrzycki** [comment]
I confirm that it is a bug, especially for inputs. If we have an input with pull-up enabled, the default state is '1', but the library returns 0 as long as there was no transition on that input.
So, at least here:
https://github.com/EnotionZ/GpiO/blob/master/lib/gpio.js#L104
you have to manually read the value and store it. The same situation is for output because you have no guarantee that something before your applications, changed the output value.

**Comment by rzr** [comment]
@mmajchrzycki please confirm linked patch is working.
I have to do similar fixes app's side so I thought this can be done internally with:

https://github.com/TizenTeam/GpiO/commit/2a6df5812231877e0212301b6be8c242aa923963#diff-7185c21331efab29ab056d18eee6d632R117

**Comment by EnotionZ** [comment]
The patch was already merged into master. Tests are in #58 and will be merged into v1 branch. Closing issue.
